---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/motorcycles":
    get:
      summary: list motorcycles
      parameters:
      - name: Authorization
        in: header
        description: an authorization header
        required: false
        schema:
          type: string
      responses:
        '200':
          description: successful
    post:
      summary: create motorcycle
      parameters:
      - name: Authorization
        in: header
        description: an authorization header
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
  "/motorcycles/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    - name: Authorization
      in: header
      description: an authorization header
      required: true
      schema:
        type: string
    get:
      summary: show motorcycle
      responses:
        '200':
          description: successful
    delete:
      summary: delete motorcycle
      responses:
        '200':
          description: successful
  "/reservations":
    parameters:
    - name: Authorization
      in: header
      description: an authorization header
      required: true
      schema:
        type: string  
    get:
      summary: list reservations
      responses:
        '200':
          description: successful
    post:
      summary: create reservation
      responses:
        '200':
          description: successful
  "/reservations/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    - name: Authorization
      in: header
      description: an authorization header
      required: true
      schema:
        type: string  
    delete:
      summary: delete reservation
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
