default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>

development:
  <<: *default
  database: appointment_app_backend_development
  username: <%= ENV.fetch('DATABASE_USERNAME', '') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', '') %>

test:
  <<: *default
  database: appointment_app_backend_test
  username: <%= ENV.fetch('DATABASE_USERNAME', '') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', '') %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: c00p75_db
  username: c00p75
  password: <%= ENV.fetch('APPOINTMENT_APP_BACKEND_DATABASE_PASSWORD') %>
