default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: appointment_app_backend_development
  username: <%= ENV.fetch('DATABASE_USERNAME', '') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', '') %>
  password: <%= ENV.fetch('DATABASE_PORT', '') %>

test:
  <<: *default
  database: appointment_app_backend_test
  username: <%= ENV.fetch('DATABASE_USERNAME', '') %>
  password: <%= ENV.fetch('DATABASE_PORT', '') %>

production:
  <<: *default
  database: appointment_app_backend_production
  username: appointment_app_backend
  password: <%= ENV["APPOINTMENT_APP_BACKEND_DATABASE_PASSWORD"] %>
